
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>


development:
  <<: *default
  database: osn_app_development
  host: db
  username: root
  password: password

test:
  <<: *default
  database: osn_app_test
  host: db
  username: root
  password: password

production:
  primary: &primary_production
    <<: *default
    url: <%= ENV['DATABASE_URL'] %>
